<?php

/**
 * @file
 * Defines the Freebie entity and associated features.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function commerce_freebie_theme() {
  return [
    'commerce_freebie' => [
      'render element' => 'elements',
    ],
    'commerce_freebie_selection_form' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_commerce_freebie().
 */
function commerce_freebie_theme_suggestions_commerce_freebie(array $variables) {
  return _commerce_entity_theme_suggestions('commerce_freebie', $variables);
}

/**
 * Prepares variables for freebie templates.
 *
 * Default template: commerce-freebie.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing rendered fields.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_commerce_freebie(array &$variables) {
  /** @var Drupal\commerce_freebie\Entity\FreebieInterface $freebie */
  $freebie = $variables['elements']['#commerce_freebie'];

  $variables['label'] = $freebie->label();
  $variables['sku'] = $freebie->getSku();
  $variables['content'] = [];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_views_data_alter().
 *
 * Workaround for https://www.drupal.org/project/weight/issues/2887710.
 */
function commerce_freebie_views_data_alter(array &$data) {
  $table_data = &$data['commerce_freebie'];
  $field_name = 'priority';

  $table_data[$field_name . '_value']['field'] = $table_data[$field_name]['field'];
  $title = t('@title Selector (@field)', [
    '@title' => $table_data[$field_name]['title'],
    '@field' => $field_name,
  ]);
  $short_title = t('@title Selector', ['@title' => $table_data[$field_name]['title']]);
  $table_data[$field_name]['title'] = $title;
  $table_data[$field_name]['title short'] = $short_title;
  $table_data[$field_name]['field']['id'] = 'weight_selector';
}
